syntax = "proto3";

package surimi.v1;

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message CreateExperimentRequest {
  // This experiment_id identifies the experiment this request belongs to
  string experiment_id = 1;
  // The list of simulation_ids that are part of this experiment
  repeated string simulation_ids = 2;
}

// The response message of CreateExperimentRequest
message CreateExperimentResponse {
  // This experiment_id identifies the experiment this request belongs to
  string experiment_id = 1;
}

// The aggregator service
service AggregatorService {
  // Create an experiment consisting of a list of simulations
  rpc CreateExperiment(CreateExperimentRequest) returns (CreateExperimentResponse);
}