syntax = "proto3";

package surimi.v1;

import "buf/validate/validate.proto";
import "surimi/v1/species.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message BiomassGrid {
  Species species = 1;
  repeated BiomassCell biomass_cells = 2;
}

// center of the cell
message BiomassCell {
  double longitude = 1 [(buf.validate.field).double = {
    gte: -180
    lte: 180
  }];
  double latitude = 2 [(buf.validate.field).double = {
    gte: -90
    lte: 90
  }];
  double biomass = 3;
}

// The summary of the biomass, containing a list of BiomassGrids.
// This is the object that the controller can copy from the server to its clients
message BiomassSummary {
  repeated BiomassGrid biomass_grids = 1;
}
