syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message InitSimulationRequest {
  string scenario_id = 1; // model configuration (Area, fleet, species, etc.)
  // string user_id = 2;	// user id will come from authentication
  google.protobuf.Timestamp start_date_time = 2; // start date and time of the simulation
  string step_size = 3; // time step size (e.g . 1 day, 1 month, 1 year) in ISO 8601 duration format
  // repeated string relevant_species = 4;	// list of species that are relevant for the simulation
}

message InitSimulationResponse {
  string simulation_id = 1;
}

message RunSimulationRequest {
  string simulation_id = 1;
  google.protobuf.Timestamp start_date_time = 2; // start date and time of the simulation
  string step_size = 3; // time step size (e.g . 1 day, 1 month, 1 year) in ISO 8601 duration format
  string simulation_duration = 4; // duration of the simulation (10Y) in ISO 8601 duration format
}

message RunSimulationResponse {}

service ControllerService {
  rpc InitSimulation(InitSimulationRequest) returns (InitSimulationResponse);
  rpc RunSimulation(RunSimulationRequest) returns (RunSimulationResponse);
}
