syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";
import "surimi/v1/simulation.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message InitSimulationRequest {
  Simulation simulation = 1;
}

message InitSimulationResponse {
  string simulation_id = 1;
}

message RunSimulationRequest {
  string simulation_id = 1;
  google.protobuf.Timestamp start_date_time = 2; // start date and time of the simulation
  string step_size = 3; // time step size (e.g . 1 day, 1 month, 1 year) in ISO 8601 duration format
  string simulation_duration = 4; // duration of the simulation (10Y) in ISO 8601 duration format
}

message RunSimulationResponse {
  string simulation_id = 1;
}

message GetAllSimulationsRequest {}

message GetAllSimulationsResponse {
  repeated Simulation simulations = 1; // list of all simulations
}

service ControllerService {
  rpc InitSimulation(InitSimulationRequest) returns (InitSimulationResponse);
  rpc RunSimulation(RunSimulationRequest) returns (RunSimulationResponse);
  rpc GetAllSimulations(GetAllSimulationsRequest) returns (GetAllSimulationsResponse);
}
