syntax = "proto3";

package surimi.v1;

import "surimi/v1/get_all_simulation_statuses.proto";
import "surimi/v1/get_simulation_contract.proto";
import "surimi/v1/remove_experiment.proto";
import "surimi/v1/submit_experiment.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// The ControllerService is called to send commands to the simulation controller. For example by a GUI.
// It's also used to check the status of all simulations, so the GUI can display them.
service ControllerService {
  // Submits a new experiment with the given scenario_name, an experiment_id and the requested end date and time.
  rpc SubmitExperiment(SubmitExperimentRequest) returns (SubmitExperimentResponse);
  // Removes the experiment with the given experiment_id.
  rpc RemoveExperiment(RemoveExperimentRequest) returns (RemoveExperimentResponse);
  // Gets the statuses of all simulations. This method can be periodically called by a GUI to update the list of simulations and their statuses.
  rpc GetAllSimulationStatuses(GetAllSimulationStatusesRequest) returns (GetAllSimulationStatusesResponse);
  // Gets the simulation contract. This method can be used by, for example, the GUI to get the simulation contract, so it can check which species codes, port codes, gear codes, etc. are used in the simulation.
  // This method reads the yaml file and returns the simulation contract.
  rpc GetSimulationContract(GetSimulationContractRequest) returns (GetSimulationContractResponse);
}
