syntax = "proto3";

package surimi.v1;

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// 3 letter country code (ISO 3166-1 alpha-3)
enum Country {
  COUNTRY_UNSPECIFIED = 0;
  COUNTRY_AFG = 1;
  COUNTRY_ALA = 2;
  COUNTRY_ALB = 3;
  COUNTRY_DZA = 4;
  COUNTRY_ASM = 5;
  COUNTRY_AND = 6;
  COUNTRY_AGO = 7;
  COUNTRY_AIA = 8;
  COUNTRY_ATA = 9;
  COUNTRY_ATG = 10;
  COUNTRY_ARG = 11;
  COUNTRY_ARM = 12;
  COUNTRY_ABW = 13;
  COUNTRY_AUS = 14;
  COUNTRY_AUT = 15;
  COUNTRY_AZE = 16;
  COUNTRY_BHS = 17;
  COUNTRY_BHR = 18;
  COUNTRY_BGD = 19;
  COUNTRY_BRB = 20;
  COUNTRY_BLR = 21;
  COUNTRY_BEL = 22;
  COUNTRY_BLZ = 23;
  COUNTRY_BEN = 24;
  COUNTRY_BMU = 25;
  COUNTRY_BTN = 26;
  COUNTRY_BOL = 27;
  COUNTRY_BES = 28;
  COUNTRY_BIH = 29;
  COUNTRY_BWA = 30;
  COUNTRY_BVT = 31;
  COUNTRY_BRA = 32;
  COUNTRY_IOT = 33;
  COUNTRY_BRN = 34;
  COUNTRY_BGR = 35;
  COUNTRY_BFA = 36;
  COUNTRY_MMR = 37;
  COUNTRY_BDI = 38;
  COUNTRY_KHM = 39;
  COUNTRY_CMR = 40;
  COUNTRY_CAN = 41;
  COUNTRY_CPV = 42;
  COUNTRY_CYM = 43;
  COUNTRY_CAF = 44;
  COUNTRY_TCD = 45;
  COUNTRY_CHL = 46;
  COUNTRY_CHN = 47;
  COUNTRY_CXR = 48;
  COUNTRY_CCK = 49;
  COUNTRY_COL = 50;
  COUNTRY_COM = 51;
  COUNTRY_COD = 52;
  COUNTRY_COG = 53;
  COUNTRY_COK = 54;
  COUNTRY_CRI = 55;
  COUNTRY_CIV = 56;
  COUNTRY_HRV = 57;
  COUNTRY_CUB = 58;
  COUNTRY_CUW = 59;
  COUNTRY_CYP = 60;
  COUNTRY_CZE = 61;
  COUNTRY_DNK = 62;
  COUNTRY_DJI = 63;
  COUNTRY_DMA = 64;
  COUNTRY_DOM = 65;
  COUNTRY_ECU = 66;
  COUNTRY_EGY = 67;
  COUNTRY_SLV = 68;
  COUNTRY_GNQ = 69;
  COUNTRY_ERI = 70;
  COUNTRY_EST = 71;
  COUNTRY_ETH = 72;
  COUNTRY_FLK = 73;
  COUNTRY_FRO = 74;
  COUNTRY_FJI = 75;
  COUNTRY_FIN = 76;
  COUNTRY_FRA = 77;
  COUNTRY_GUF = 78;
  COUNTRY_PYF = 79;
  COUNTRY_ATF = 80;
  COUNTRY_GAB = 81;
  COUNTRY_GMB = 82;
  COUNTRY_GEO = 83;
  COUNTRY_DEU = 84;
  COUNTRY_GHA = 85;
  COUNTRY_GIB = 86;
  COUNTRY_GRC = 87;
  COUNTRY_GRL = 88;
  COUNTRY_GRD = 89;
  COUNTRY_GLP = 90;
  COUNTRY_GUM = 91;
  COUNTRY_GTM = 92;
  COUNTRY_GGY = 93;
  COUNTRY_GNB = 94;
  COUNTRY_GIN = 95;
  COUNTRY_GUY = 96;
  COUNTRY_HTI = 97;
  COUNTRY_HMD = 98;
  COUNTRY_VAT = 99;
  COUNTRY_HND = 100;
  COUNTRY_HKG = 101;
  COUNTRY_HUN = 102;
  COUNTRY_ISL = 103;
  COUNTRY_IND = 104;
  COUNTRY_IDN = 105;
  COUNTRY_IRN = 106;
  COUNTRY_IRQ = 107;
  COUNTRY_IRL = 108;
  COUNTRY_IMN = 109;
  COUNTRY_ISR = 110;
  COUNTRY_ITA = 111;
  COUNTRY_JAM = 112;
  COUNTRY_JPN = 113;
  COUNTRY_JEY = 114;
  COUNTRY_JOR = 115;
  COUNTRY_KAZ = 116;
  COUNTRY_KEN = 117;
  COUNTRY_KIR = 118;
  COUNTRY_PRK = 119;
  COUNTRY_KOR = 120;
  COUNTRY_XKX = 121;
  COUNTRY_KWT = 122;
  COUNTRY_KGZ = 123;
  COUNTRY_LAO = 124;
  COUNTRY_LVA = 125;
  COUNTRY_LBN = 126;
  COUNTRY_LSO = 127;
  COUNTRY_LBR = 128;
  COUNTRY_LBY = 129;
  COUNTRY_LIE = 130;
  COUNTRY_LTU = 131;
  COUNTRY_LUX = 132;
  COUNTRY_MAC = 133;
  COUNTRY_MKD = 134;
  COUNTRY_MDG = 135;
  COUNTRY_MWI = 136;
  COUNTRY_MYS = 137;
  COUNTRY_MDV = 138;
  COUNTRY_MLI = 139;
  COUNTRY_MLT = 140;
  COUNTRY_MHL = 141;
  COUNTRY_MTQ = 142;
  COUNTRY_MRT = 143;
  COUNTRY_MUS = 144;
  COUNTRY_MYT = 145;
  COUNTRY_MEX = 146;
  COUNTRY_FSM = 147;
  COUNTRY_MDA = 148;
  COUNTRY_MCO = 149;
  COUNTRY_MNG = 150;
  COUNTRY_MNE = 151;
  COUNTRY_MSR = 152;
  COUNTRY_MAR = 153;
  COUNTRY_MOZ = 154;
  COUNTRY_NAM = 155;
  COUNTRY_NRU = 156;
  COUNTRY_NPL = 157;
  COUNTRY_ANT = 158;
  COUNTRY_NLD = 159;
  COUNTRY_NCL = 160;
  COUNTRY_NZL = 161;
  COUNTRY_NIC = 162;
  COUNTRY_NER = 163;
  COUNTRY_NGA = 164;
  COUNTRY_NIU = 165;
  COUNTRY_NFK = 166;
  COUNTRY_MNP = 167;
  COUNTRY_NOR = 168;
  COUNTRY_OMN = 169;
  COUNTRY_PAK = 170;
  COUNTRY_PLW = 171;
  COUNTRY_PSE = 172;
  COUNTRY_PAN = 173;
  COUNTRY_PNG = 174;
  COUNTRY_PRY = 175;
  COUNTRY_PER = 176;
  COUNTRY_PHL = 177;
  COUNTRY_PCN = 178;
  COUNTRY_POL = 179;
  COUNTRY_PRT = 180;
  COUNTRY_PRI = 181;
  COUNTRY_QAT = 182;
  COUNTRY_REU = 183;
  COUNTRY_ROU = 184;
  COUNTRY_RUS = 185;
  COUNTRY_RWA = 186;
  COUNTRY_BLM = 187;
  COUNTRY_SHN = 188;
  COUNTRY_KNA = 189;
  COUNTRY_LCA = 190;
  COUNTRY_MAF = 191;
  COUNTRY_SPM = 192;
  COUNTRY_VCT = 193;
  COUNTRY_WSM = 194;
  COUNTRY_SMR = 195;
  COUNTRY_STP = 196;
  COUNTRY_SAU = 197;
  COUNTRY_SEN = 198;
  COUNTRY_SRB = 199;
  COUNTRY_SYC = 200;
  COUNTRY_SLE = 201;
  COUNTRY_SGP = 202;
  COUNTRY_SXM = 203;
  COUNTRY_SVK = 204;
  COUNTRY_SVN = 205;
  COUNTRY_SLB = 206;
  COUNTRY_SOM = 207;
  COUNTRY_ZAF = 208;
  COUNTRY_SGS = 209;
  COUNTRY_SSD = 210;
  COUNTRY_ESP = 211;
  COUNTRY_LKA = 212;
  COUNTRY_SDN = 213;
  COUNTRY_SUR = 214;
  COUNTRY_SJM = 215;
  COUNTRY_SWZ = 216;
  COUNTRY_SWE = 217;
  COUNTRY_CHE = 218;
  COUNTRY_SYR = 219;
  COUNTRY_TWN = 220;
  COUNTRY_TJK = 221;
  COUNTRY_TZA = 222;
  COUNTRY_THA = 223;
  COUNTRY_TLS = 224;
  COUNTRY_TGO = 225;
  COUNTRY_TKL = 226;
  COUNTRY_TON = 227;
  COUNTRY_TTO = 228;
  COUNTRY_TUN = 229;
  COUNTRY_TUR = 230;
  COUNTRY_TKM = 231;
  COUNTRY_TCA = 232;
  COUNTRY_TUV = 233;
  COUNTRY_UGA = 234;
  COUNTRY_UKR = 235;
  COUNTRY_ARE = 236;
  COUNTRY_GBR = 237;
  COUNTRY_UMI = 238;
  COUNTRY_USA = 239;
  COUNTRY_URY = 240;
  COUNTRY_UZB = 241;
  COUNTRY_VUT = 242;
  COUNTRY_VEN = 243;
  COUNTRY_VNM = 244;
  COUNTRY_VGB = 245;
  COUNTRY_VIR = 246;
  COUNTRY_WLF = 247;
  COUNTRY_ESH = 248;
  COUNTRY_YEM = 249;
  COUNTRY_ZMB = 250;
  COUNTRY_ZWE = 251;
}
