syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";
import "surimi/v1/biomass.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message GetBiomassRequest {
  string simulation_id = 1;
  google.protobuf.Timestamp start_date_time = 2;
  google.protobuf.Timestamp end_date_time = 3;
}

message GetBiomassResponse {
  string simulation_id = 1;
  google.protobuf.Timestamp start_date_time = 2;
  google.protobuf.Timestamp end_date_time = 3;
  BiomassSummary biomass_summary = 4;
}

message UpdateBiomassRequest {
  string simulation_id = 1;
  google.protobuf.Timestamp start_date_time = 2;
  google.protobuf.Timestamp end_date_time = 3;
  BiomassSummary biomass_summary = 4;
}

message UpdateBiomassResponse {
  string simulation_id = 1;
}

// The ecology service definition contaisns methods that have to do with ecology. It contaisns methods to get and update biomass information
service EcologyService {
  // Get the biomass information for a simulation
  rpc GetBiomass(GetBiomassRequest) returns (GetBiomassResponse);
  // Update the biomass information
  rpc UpdateBiomass(UpdateBiomassRequest) returns (UpdateBiomassResponse);
}
