syntax = "proto3";

package surimi.v1;

import "surimi/v1/biomass.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message GetBiomassRequest {
  string simulation_id = 1;
}

message GetBiomassResponse {
  string simulation_id = 1;
  BiomassSummary biomass_summary = 2;
}

message UpdateBiomassRequest {
  string simulation_id = 1;
  BiomassSummary biomass_summary = 2;
}

message UpdateBiomassResponse {
  string simulation_id = 1;
}

service EcologyService {
  rpc GetBiomass(GetBiomassRequest) returns (GetBiomassResponse);
  rpc UpdateBiomass(UpdateBiomassRequest) returns (UpdateBiomassResponse);
}
