syntax = "proto3";

package surimi.v1;

import "surimi/v1/cancel_experiment.proto";
import "surimi/v1/experiment_step.proto";
import "surimi/v1/finalise_experiment.proto";
import "surimi/v1/get_environment_variables.proto";
import "surimi/v1/get_protocol_version.proto";
import "surimi/v1/initialise_experiment.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// The Environment service has to be implemented by services that provide environment information
service EnvironmentService {
  // Initialises the list of simulations belonging to an experiment
  rpc InitialiseExperiment(InitialiseExperimentRequest) returns (InitialiseExperimentResponse);
  // This call requests the model to simulate a single time step. The model can perform all calculations.
  rpc ExperimentStep(ExperimentStepRequest) returns (ExperimentStepResponse);
  // Cancel the experiment.
  rpc CancelExperiment(CancelExperimentRequest) returns (CancelExperimentResponse);
  // Finalises the experiment, which means that all the results of the simulations will be aggregated and stored in a file
  rpc FinaliseExperiment(FinaliseExperimentRequest) returns (FinaliseExperimentResponse);
  // This method can be used to get the version of the protobuf files. It returns the protocol_version of the SDK.
  rpc GetProtocolVersion(GetProtocolVersionRequest) returns (GetProtocolVersionResponse);

  // Get the EnvironmentVariables information for a simulation
  rpc GetEnvironmentVariables(GetEnvironmentVariablesRequest) returns (GetEnvironmentVariablesResponse);
}
