syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";
import "surimi/v1/environment_variables.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// Message that is sent to request the Environment Variables at a specific moment in time
message GetEnvironmentVariablesRequest {
  // This simulation_id identifies the simulation this request belongs to
  string simulation_id = 1;
  // The moment the EnvironmentVariables is requested for
  google.protobuf.Timestamp date_time = 2;
}

// This message returns the Environment Variables at the moment of date_time
message GetEnvironmentVariablesResponse {
  // This simulation_id identifies the simulation this request belongs to
  string simulation_id = 1;
  // The moment that these Environment Variables apply to
  google.protobuf.Timestamp date_time = 2;
  // The EnvironmentVariables summary
  EnvironmentVariablesSummary environment_variables_summary = 3;
}

// The Environment provider service has to be implemented by services that provide environment information
service EnvironmentProviderService {
  // Get the EnvironmentVariables information for a simulation
  rpc GetEnvironmentVariables(GetEnvironmentVariablesRequest) returns (GetEnvironmentVariablesResponse);
}
