syntax = "proto3";

package surimi.v1;

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// The grid of the environment variables for a given variable code. It contains a list of EnvironmentVariablesCells, each containing the value of the variable in a cell with a given longitude and latitude.
message EnvironmentVariablesGrid {
  // the name of the variable, e.g. "sea_surface_temperature", "chlorophyll_concentration", etc.
  string variable_code = 1;
  repeated EnvironmentVariablesCell environment_variables_cells = 2;
}

// The environmental variables in this cell.
message EnvironmentVariablesCell {
  // The longitude of the cell, in degree_east
  double longitude = 1;
  // The latitude of the cell, in degree_north
  double latitude = 2;
  // The value of the variable in this cell.
  double value = 3;
}

// The summary of the environment variables, containing a list of EnvironmentVariablesGrids.
// This is the object that the controller can copy from the server to its clients
message EnvironmentVariablesSummary {
  repeated EnvironmentVariablesGrid environment_variables_grids = 1;
}
