syntax = "proto3";

package surimi.v1;

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// The request message of FinaliseExperimentRequest
message FinaliseExperimentRequest {
  // This experiment_id identifies the experiment this request belongs to
  string experiment_id = 1;
}

// The response message of FinaliseExperimentRequest
message FinaliseExperimentResponse {
  // This experiment_id identifies the experiment this request belongs to
  string experiment_id = 1;
}
