syntax = "proto3";

package surimi.v1;

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message FleetSegment {
  // max 3 chars code. PS, TBB etc. see https://openknowledge.fao.org/handle/20.500.14283/cb4966en
  string gear_code = 1;
  // see https://dcf.ec.europa.eu/data-calls/definitions-and-terminology/f/fleet-segment-dcf-eu-map_en
  string vessel_length_class = 2;
  // the scale of the fishing operation, e.g. "Artisanal" "Industrial" "Indigenous"
  string scale = 3;
  // 3 letter country code (ISO 3166-1 alpha-3)
  string country_code = 4;
  // the model that simulates this fleet segment. For example "EwE" or "POSEIDON"
  string model = 5;
}
