syntax = "proto3";

package surimi.v1;

import "surimi/v1/simulation_status.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// This message is send periodically to request the status of all experiments and simulations
message GetAllSimulationStatusesRequest {}

// The answer message containing the status of all experiments and simulations
message GetAllSimulationStatusesResponse {
  // list of all simulation statuses
  repeated SimulationStatus simulation_statuses = 1;
}
