syntax = "proto3";

package surimi.v1;

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// This message is used to request the version of the protobuf files. It doesn't contain any fields, as it is just a request to get the version.
message GetProtocolVersionRequest {}

// This message is used to respond to the GetProtocolVersionRequest. It contains the protocol_version of the SDK, which is a string that describes the version of the protobuf files. This can be used by the model to check if it is compatible with the controller.
message GetProtocolVersionResponse {
  string protocol_version = 1;
}
