syntax = "proto3";

package surimi.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "surimi/v1/simulation.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message InitialiseExperimentRequest {
  // This experiment_id identifies the experiment this request belongs to
  string experiment_id = 1;
  // The list of simulation_ids that are part of this experiment
  repeated string simulation_ids = 2;
  // the Simulation contract.
  Simulation simulation = 3;
  // The name of the scenario that is used. It must not be empty.
  string scenario_name = 4 [(buf.validate.field).string = {min_len: 1}];
  // The end date time of the simulation. This may be earlier that the maximum end date time that is specified in the Simulation contract.
  google.protobuf.Timestamp end_date_time = 5;
  // The climate scenario that is used in the experiment. This is a string that identifies the climate scenario, like "RCP_2.6", "RCP_4.5" It must not be empty.
  string climate_scenario = 6 [(buf.validate.field).string = {min_len: 1}];
  // Defines if its an MSE (Management Strategy Evaluation) run. So if the experiment will run multiple simulations or not. The exact number of simulations will be determined by the Controller
  bool is_mse_run = 7;
}

// The response message of InitialiseExperimentRequest
message InitialiseExperimentResponse {
  // This experiment_id identifies the experiment this request belongs to
  string experiment_id = 1;
}
