syntax = "proto3";

package surimi.v1;

import "surimi/v1/currency.proto";
import "surimi/v1/fleet_segment.proto";
import "surimi/v1/market.proto";
import "surimi/v1/price_category.proto";
import "surimi/v1/species.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message Items {
  repeated Market markets = 1;
  repeated Currency currencies = 2;
  repeated Species species = 3;
  repeated FleetSegment fleet_segments = 4;
  repeated PriceCategory price_categories = 5;
}
