syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";
import "surimi/v1/sales.proto";
import "surimi/v1/species_price.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// Message that is sent to request the Species prices at a specific moment in time
message GetSpeciesPricesRequest {
  // This simulation_id identifies the simulation this request belongs to
  string simulation_id = 1;
  // The moment the Species prices are requested for
  google.protobuf.Timestamp date_time = 2;
}

// This message returns the Species prices at a specific moment in time
message GetSpeciesPricesResponse {
  // This simulation_id identifies the simulation this request belongs to
  string simulation_id = 1;
  // The moment that these Species prices apply to
  google.protobuf.Timestamp date_time = 2;
  // The Species prices summary
  repeated SpeciesPrice prices = 3;
}

// This Message is sent to update the sales summaries for a given simulation and time period. The sales are used to calculate the Species prices for the next time period.
message UpdateSalesRequest {
  // This simulation_id identifies the simulation this request belongs to
  string simulation_id = 1;
  // The start of the time period for which the sales summaries are being updated
  google.protobuf.Timestamp start_date_time = 2;
  // The end of the time period for which the sales summaries are being updated
  google.protobuf.Timestamp end_date_time = 3;
  // The sales summaries to be updated
  repeated SalesSummary sales_summaries = 4;
}

message UpdateSalesResponse {
  // This simulation_id identifies the simulation this response belongs to
  string simulation_id = 1;
}

// The market provider service must be implemented by the market model. It provides species prices and consumes sales to calculate the prices with
service MarketProviderService {
  // This method is used to retrieve the species prices for a given simulation.
  rpc GetSpeciesPrices(GetSpeciesPricesRequest) returns (GetSpeciesPricesResponse);
  // This method is used to update the sales summaries for a given simulation and time period.
  rpc UpdateSales(UpdateSalesRequest) returns (UpdateSalesResponse);
}
