syntax = "proto3";

option csharp_namespace = "Surimi";
option java_package = "eu.project.surimi";

package surimi.v1;

import "google/protobuf/empty.proto";
import "surimi/v1/species_price.proto";

service MarketService {
    rpc GetSpeciesPrices (google.protobuf.Empty) returns (SpeciesPrices);

    //rpc SendUpdatePrices (EmptyRequest) returns (stream MarketMessage);
    //rpc TriggerUpdate (EmptyRequest) returns (EmptyRequest);
    //rpc StartSimulation (SimulationRequest) returns (EmptyRequest);
}
