syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";
import "surimi/v1/sales.proto";
import "surimi/v1/species_price.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message GetSpeciesPricesRequest {
  string simulation_id = 1;
}

message GetSpeciesPricesResponse {
  string simulation_id = 1;
  repeated SpeciesPrice prices = 2;
}

message UpdateSpeciesPricesRequest {
  string simulation_id = 1;
  // When filled, this simulation is part on an experiment consisting of many simulations. The Controller should fill the experiment_id
  string experiment_id = 2;
  repeated SpeciesPrice prices = 3;
}

message UpdateSpeciesPricesResponse {
  string simulation_id = 1;
}

message GetSalesRequest {
  string simulation_id = 1;
  google.protobuf.Timestamp start_date_time = 2;
  google.protobuf.Timestamp end_date_time = 3;
}

message GetSalesResponse {
  string simulation_id = 1;
  google.protobuf.Timestamp start_date_time = 2;
  google.protobuf.Timestamp end_date_time = 3;
  repeated SalesSummary sales_summaries = 4;
}

message UpdateSalesRequest {
  string simulation_id = 1;
  // When filled, this simulation is part on an experiment consisting of many simulations. The Controller should fill the experiment_id
  string experiment_id = 2;
  google.protobuf.Timestamp start_date_time = 3;
  google.protobuf.Timestamp end_date_time = 4;
  repeated SalesSummary sales_summaries = 5;
}

message UpdateSalesResponse {
  string simulation_id = 1;
}

// The market service definition contains methods that have to do with market data. It contains methods to get And update species prices And sales.
service MarketService {
  // This method is used to retrieve the species prices for a given simulation.
  rpc GetSpeciesPrices(GetSpeciesPricesRequest) returns (GetSpeciesPricesResponse);
  // This method is used to update the species prices for a given simulation.
  rpc UpdateSpeciesPrices(UpdateSpeciesPricesRequest) returns (UpdateSpeciesPricesResponse);
  // This method is used to retrieve the sales summaries for a given simulation and time period.
  rpc GetSales(GetSalesRequest) returns (GetSalesResponse);
  // This method is used to update the sales summaries for a given simulation and time period.
  rpc UpdateSales(UpdateSalesRequest) returns (UpdateSalesResponse);
}
