syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";
import "surimi/v1/fishing_activity.proto";
import "surimi/v1/regulation.proto";
import "surimi/v1/regulation_definition.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message GetRegulationsRequest {
  string simulation_id = 1;
  google.protobuf.Timestamp start_date_time = 2;
  google.protobuf.Timestamp end_date_time = 3;
}

message GetRegulationsResponse {
  string simulation_id = 1;
  google.protobuf.Timestamp start_date_time = 2;
  google.protobuf.Timestamp end_date_time = 3;
  RegulationsSummary regulations_summary = 4;
}

message UpdateFishingActivityRequest {
  string simulation_id = 1;
  google.protobuf.Timestamp start_date_time = 2;
  google.protobuf.Timestamp end_date_time = 3;
  FishingActivitySummary fishing_activity_summary = 4;
}

message UpdateFishingActivityResponse {
  string simulation_id = 1;
}

// This message is sent to the Regulations Provider. It contains a set of regulation definitions that are created to do the simulation with.
message CreateRegulationsRequest {
  string simulation_id = 1;
  RegulationDefinitionsSummary regulations_summary = 2;
}

message CreateRegulationsResponse {
  string simulation_id = 1;
}

// The regulations provider service has to be implemented by services that provide regulations, such as the fishery authority. In turn, it receives fishing activity to gather feedback of the regulations
service RegulationsProviderService {
  // This method is used to retrieve all Harvest Control Regulations for the specified period.
  rpc GetRegulations(GetRegulationsRequest) returns (GetRegulationsResponse);
  // This method has to be implemented to receive the fishing activity needed to calculate the new regulations
  rpc UpdateFishingActivity(UpdateFishingActivityRequest) returns (UpdateFishingActivityResponse);
  // This method is used to create the Harvest Control Regulations.
  rpc CreateRegulations(CreateRegulationsRequest) returns (CreateRegulationsResponse);
}
