syntax = "proto3";

package surimi.v1;

import "surimi/v1/fleet_segment.proto";
import "surimi/v1/species.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// Describes the Species, and the total allowable catch for this timestep
message TotalAllowableCatch {
  // The species that this is about
  Species species = 1;
  // The fleet segment that this is about
  FleetSegment fleet_segment = 2;
  // The total allowable catch for this species and fleet segment
  double catch = 3;
}

// This message contains all regulations that apply to this timestep
message RegulationsSummary {
  repeated TotalAllowableCatch total_allowable_catches = 1;
}
