syntax = "proto3";

package surimi.v1;

import "surimi/v1/species.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// Describes the Species, and the total allowable catch for this timestep
message TotalAllowableCatch {
  Species species = 1;
  double catch = 2;
}

message AllowedTime {
  Species species = 1;
  // TODO. Describe the time that this Species can be caught
}

// This message contains all regulations that apply to this timestep
message RegulationsSummary {
  repeated TotalAllowableCatch total_allowable_catches = 1;
  repeated AllowedTime allowed_timer = 2;
}
