syntax = "proto3";

package surimi.v1;

import "surimi/v1/fleet_segment.proto";
import "surimi/v1/species.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message Sale {
  // The species that is being sold. This can be one of the species specified in the contract.
  Species species = 1;
  // The fleet segment that is making the sale. This can be one of the fleet segments specified in the contract.
  FleetSegment fleet_segment = 2;
  // The quantity of the sale, in the unit specified in the contract. This will typically be in Kg.
  double quantity = 3;
  // The value of the Sale, in the currency specified in the MarketSales.
  double value = 4;
}

message MarketSales {
  // The market_code can be one of the market codes specified in the contract.
  string market_code = 1;
  // The currency of the sales. This can be one of the currencies specified in the contract.
  string currency = 2;
  // A collection of sales that are made in the specified market, for this time period.
  repeated Sale sales = 3;
}

message SalesSummary {
  // The market sales summary for this time period
  repeated MarketSales market_sales = 1;
}
