syntax = "proto3";

package surimi.v1;

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message Sale {
  string species_code = 1;
  double quantity = 2;
  double value = 3;
}

message SalesSummary {
  string market_code = 1; // for the western med case, 2 letter country code (ISO 3166-1 alpha-2) plus 3 letter port code according to https://unece.org/trade/cefact/unlocode-code-list-country-and-territory
  string measurement_unit = 2;
  string currency = 3;
  repeated Sale sales = 4;
}
