syntax = "proto3";

package surimi.v1;

import "surimi/v1/double_statistics.proto";
import "surimi/v1/fleet_segment.proto";
import "surimi/v1/species.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message SaleStatistics {
  Species species = 1;
  FleetSegment fleet_segment = 2;
  double quantity = 3;
  DoubleStatistics value = 4;
}

message MarketSalesStatistics {
  // for the western med case, 2 letter country code (ISO 3166-1 alpha-2) plus 3 letter port code according to https://unece.org/trade/cefact/unlocode-code-list-country-and-territory
  string market_code = 1;
  string currency = 2;
  repeated SaleStatistics sales_statistics = 3;
}

message SalesStatisticsSummary {
  // The market sales summaries for this time period
  repeated MarketSalesStatistics market_sales_statistics = 1;
}
