syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";
import "surimi/v1/simulation.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// Request messages for SimulationService
message InitialiseRequest {
  // this is the ID of 1 simulation.
  string simulation_id = 1;
  // the Simulation contract.
  Simulation simulation = 2;
  // The name of the scenario that is used.
  string scenario_id = 3;
  // The end date time of the simulation. This may be earlier that the maximum end date time that is specified in the Simulation contract.
  google.protobuf.Timestamp end_date_time = 4;
}

// The Response message
message InitialiseResponse {
  // this is the ID of 1 simulation.
  string simulation_id = 1;
}

message FinaliseRequest {
  string simulation_id = 1;
}

message FinaliseResponse {
  string simulation_id = 1;
}

message CancelRequest {
  string simulation_id = 1;
}

message CancelResponse {
  string simulation_id = 1;
}

message SimulateStepRequest {
  string simulation_id = 1;
  // current date and time of the simulation
  google.protobuf.Timestamp current_date_time = 2;
}

message SimulateStepResponse {
  string simulation_id = 1;
}

// This message is used to request the version of the protobuf files. It doesn't contain any fields, as it is just a request to get the version.
message GetProtocolVersionRequest {}

// This message is used to respond to the GetProtocolVersionRequest. It contains the protocol_version of the SDK, which is a string that describes the version of the protobuf files. This can be used by the model to check if it is compatible with the controller.
message GetProtocolVersionResponse {
  string protocol_version = 1;
}

// The simulation service definition. It controlls initialising, starting, canceling And finalising a simulation.  All models should implement this interface.
service SimulationService {
  // Initialise a new simulation
  // The InitialiseRequest message contains a 'contract' of the simulation, describing the context in which the simulation will run.
  // It will contain, for example, a list of all possible SpeciesCodes, PortCodes, GearCodes, etc. that the simulation may use.
  // The model should inspect the contract and check if it can honor the contract. So if the model understands the speciesCodes, PortCodes, GearCodes, etc. listed in the contract.
  // And if the model uses the same units, coordinate reference system, time step size, etc. as described in the contract.
  // And that the model won't send back data that is not part of the contract.
  // The InitialiseRequest message also contains the start date of the simulation, the maximum end date of the simulation and the step size.
  // If the model cannot honor the contract, it should throw a GrpcException, containing a descriptive error message.
  //
  // The controller creates the InitialiseRequest.Simulation object by reading a yaml configuration file that describes the scenario to be simulated.
  rpc Initialise(InitialiseRequest) returns (InitialiseResponse);
  // This call requests the model to simulate a single time step. The model can perform all calculations.
  rpc SimulateStep(SimulateStepRequest) returns (SimulateStepResponse);
  // Finalise the simulation. The model can create a report, free resources, etc.
  rpc Finalise(FinaliseRequest) returns (FinaliseResponse);
  // Cancel the simulation. Should only be handled during the "running" state of the simulation.
  rpc Cancel(CancelRequest) returns (CancelResponse);
  // This method can be used to get the version of the protobuf files. It returns the protocol_version of the SDK.
  rpc GetProtocolVersion(GetProtocolVersionRequest) returns (GetProtocolVersionResponse);
}
