syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";
import "surimi/v1/geography.proto";
import "surimi/v1/items.proto";
import "surimi/v1/standards.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message Simulation {
  string case_study_name = 1; // model configuration (Area, fleet, species, etc.)
  google.protobuf.Timestamp start_date_time = 2; // start date and time of the simulation
  google.protobuf.Timestamp maximum_end_date_time = 3; // maximum end date and time of the simulation
  string time_step = 4; // time step size (e.g . 1 day, 1 month, 1 year) in ISO 8601 duration format
  Geography geography = 5;
  Standards standards = 6;
  Items items = 7;
}
