syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message SpeciesPrice {
  string species_code = 1; // 3-alpha code of https://www.fao.org/fishery/en/collection/asfis
  string market_code = 2; // for the western med case, 2 letter country code (ISO 3166-1 alpha-2) plus 3 letter port code according to https://unece.org/trade/cefact/unlocode-code-list-country-and-territory
  string gear_code = 3; // max 3 chars code. PS, TBB etc. see https://openknowledge.fao.org/handle/20.500.14283/cb4966en
  double price = 4;
  string measurement_unit = 5; // https://ucum.org/ucum
  string currency = 6; // 3 letter Currency Code as described in ISO 4217 . GBP, EUR, USD
  google.protobuf.Timestamp timestamp = 7;
}
