syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message SpeciesPrice {
  string market_id = 1;
  string category_code = 2;
  string species_code = 3; // 3-alpha code of https://www.fao.org/fishery/en/collection/asfis
  double price = 4;
  string currency = 5; // 3 letter Currency Code as described in ISO 4217 . GBP, EUR, USD
  string measurement_unit = 6; // https://ucum.org/ucum
  google.protobuf.Timestamp timestamp = 7;
}
