syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";
import "surimi/v1/species_price_statistics.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// this message contains the prices of a list of species
message UpdateSpeciesPriceStatisticsRequest {
  string experiment_id = 1;
  // The moment that this is the price for each species
  google.protobuf.Timestamp date_time = 2;
  SpeciesPriceStatisticsSummary species_price_statistics_summary = 3;
}

// This is the answer to the UpdateSpeciesPriceStatisticsRequest
message UpdateSpeciesPriceStatisticsResponse {
  string experiment_id = 1;
}

// The species price statistics consumer service must be implemented by every service that consumes species price statistics
service SpeciesPriceStatisticsConsumerService {
  // This method is used to update the species price statistics for a given experiment.
  rpc UpdateSpeciesPriceStatistics(UpdateSpeciesPriceStatisticsRequest) returns (UpdateSpeciesPriceStatisticsResponse);
}
