syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";
import "surimi/v1/environment_variables.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// This is an output message, containing the Environment Variables at the moment of date_time
message UpdateEnvironmentVariablesRequest {
  // This experiment_id identifies the experiment this request belongs to
  string experiment_id = 1;
  // The moment that this EnvironmentVariables is calculated for
  google.protobuf.Timestamp date_time = 2;
  // The EnvironmentVariables summary
  EnvironmentVariablesSummary environment_variables_summary = 3;
}

// The response message of UpdateEnvironmentVariablesRequest
message UpdateEnvironmentVariablesResponse {
  // This experiment_id identifies the experiment this request belongs to
  string experiment_id = 1;
}
