syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message InitialiseRequest {
  string simulation_id = 1;
  string scenario_id = 2; // model configuration (Area, fleet, species, etc.)
  // string user_id = 2;	// user id will come from authentication
  google.protobuf.Timestamp start_date_time = 3; // start date and time of the simulation
  string step_size = 4; // time step size (e.g . 1 day, 1 month, 1 year) in ISO 8601 duration format
  // repeated string relevant_species = 4;	// list of species that are relevant for the simulation
}

message InitialiseResponse {
  string simulation_id = 1;
}

message FinaliseRequest {
  string simulation_id = 1;
}

message FinaliseResponse {
  string simulation_id = 1;
}

message CancelRequest {
  string simulation_id = 1;
}

message CancelResponse {
  string simulation_id = 1;
}

message SimulateStepRequest {
  string simulation_id = 1;
}

message SimulateStepResponse {
  string simulation_id = 1;
}

// The workflow service definition. All models should implement this interface
service WorkflowService {
  rpc Initialise(InitialiseRequest) returns (InitialiseResponse);
  rpc SimulateStep(SimulateStepRequest) returns (SimulateStepResponse);
  rpc Finalise(FinaliseRequest) returns (FinaliseResponse);
  rpc Cancel(CancelRequest) returns (CancelResponse);
}
