syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";
import "surimi/v1/simulation.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

message InitialiseRequest {
  string simulation_id = 1;
  Simulation simulation = 2;
  string scenario_id = 3;
  google.protobuf.Timestamp end_date_time = 4; // end date and time of the simulation
}

message InitialiseResponse {
  string simulation_id = 1;
}

message FinaliseRequest {
  string simulation_id = 1;
}

message FinaliseResponse {
  string simulation_id = 1;
}

message CancelRequest {
  string simulation_id = 1;
}

message CancelResponse {
  string simulation_id = 1;
}

message SimulateStepRequest {
  string simulation_id = 1;
}

message SimulateStepResponse {
  string simulation_id = 1;
}

// The workflow service definition. All models should implement this interface
service WorkflowService {
  rpc Initialise(InitialiseRequest) returns (InitialiseResponse);
  rpc SimulateStep(SimulateStepRequest) returns (SimulateStepResponse);
  rpc Finalise(FinaliseRequest) returns (FinaliseResponse);
  rpc Cancel(CancelRequest) returns (CancelResponse);
}
