syntax = "proto3";

package surimi.v1;

import "google/protobuf/timestamp.proto";
import "surimi/v1/simulation.proto";

option csharp_namespace = "Grpc.Surimi";
option java_package = "eu.project.surimi";

// Request messages for WorkflowService
message InitialiseRequest {
  // this is the ID of 1 simulation.
  string simulation_id = 1;
  // the Simulation contract.
  Simulation simulation = 2;
  // The name of the scenario that is used.
  string scenario_id = 3;
  // the id of the set of regulation definitions that are part of this simulation
  string regulation_definitions_id = 4;
  // If filled, this this simulation is part of an experiment that is running multiple simulations at the same time. From the result of an experiment the variance of the values can be calculated.
  string experiment_id = 5;
}

// The Response message
message InitialiseResponse {
  // this is the ID of 1 simulation.
  string simulation_id = 1;
}

message FinaliseRequest {
  string simulation_id = 1;
}

message FinaliseResponse {
  string simulation_id = 1;
}

message CancelRequest {
  string simulation_id = 1;
}

message CancelResponse {
  string simulation_id = 1;
}

message SimulateStepRequest {
  string simulation_id = 1;
  // current date and time of the simulation
  google.protobuf.Timestamp current_date_time = 2;
}

message SimulateStepResponse {
  string simulation_id = 1;
}

// The workflow service definition. It controlls initialising, starting, canceling And finalising a simulation.  All models should implement this interface.
service WorkflowService {
  // Initialise a new simulation
  // The InitialiseRequest message contains a 'contract' of the simulation, describing the context in which the simulation will run.
  // It will contain, for example, a list of all possible SpeciesCodes, PortCodes, GearCodes, etc. that the simulation may use.
  // The model should inspect the contract and check if it can honor the contract. So if the model understands the speciesCodes, PortCodes, GearCodes, etc. listed in the contract.
  // And if the model uses the same units, coordinate reference system, time step size, etc. as described in the contract.
  // And that the model won't send back data that is not part of the contract.
  // The InitialiseRequest message also contains the start date of the simulation, the maximum end date of the simulation and the step size.
  // If the model cannot honor the contract, it should throw a GrpcException, containing a descriptive error message.
  //
  // The controller creates the InitialiseRequest.Simulation object by reading a yaml configuration file that describes the scenario to be simulated.
  rpc Initialise(InitialiseRequest) returns (InitialiseResponse);
  // This call requests the model to simulate a single time step. The model can perform all calculations.
  rpc SimulateStep(SimulateStepRequest) returns (SimulateStepResponse);
  // Finalise the simulation. The model can create a report, free resources, etc.
  rpc Finalise(FinaliseRequest) returns (FinaliseResponse);
  // Cancel the simulation. Should only be handled during the "running" state of the simulation.
  rpc Cancel(CancelRequest) returns (CancelResponse);
}
